made CC 0.4 and CC 0.4 compatible with Ultimaker PLA
Ultimaker/fdm_materials pull request #175
Opened 2021-06-25 10:48 UTC by suppomi

After this change, the following materials have the compatibility with CC 0.4 print core.
We are not sure if the PR #172 is ok only for GENERIC materials. where PLA we also have Ultimaker materials.
https://github.com/Ultimaker/fdm_materials/pull/172

2021-06-25 11:20 UTC, Ghostkeeper commented
Note: We've been asked to ignore this PR for now. Suppomi and co. are working on a different fix. I'll convert this to a draft for that reason, to indicate it's not done yet.

2021-06-25 12:00 UTC, suppomi commented
I do not have any further change for this branch.
In case if Cura team need this in next Cura release, firmware need to sync with Cura release.

2021-06-25 12:36 UTC, shanx requested changes
spotted a typo

2021-06-25 12:36 UTC, shanx commented on ultimaker_pla_orange.xml.fdm_material
> +        <version>2</version>
```suggestion
        <version>27</version>
```

2021-06-25 12:38 UTC, bryanfoley commented on ultimaker_pla_orange.xml.fdm_material
> +        <version>2</version>
Sharp :eyes:

2021-06-28 06:20 UTC, atrebelo commented
**_PLEASE DO NOT APPROVE OR MERGE THIS PR UNTIL FURTHER NOTICE_**

Message from Stijn in slack from Friday 25 June 2021

> Stijn Arntz  3 days ago

> The main reason why we have a compatibility of the CC06 core with Generic PLA is for third party materials.
> So that this profile can be used as a base for filled third party PLA's.
> Based on this it is not necessary to change the compatibility for UM PLA's right now.
> However, we would like to have a compatibility with CC04 and Generic PLA which is currently there right? <Confirmed!>

> When Sarita is back she can check how it should work for UM PLA's in my opinion.

2021-07-01 14:03 UTC, Ghostkeeper commented
Sarita referred further on to @THeijmans, who is now on vacation. Monday he'll be back apparently.

2021-07-05 07:50 UTC, Ghostkeeper approved these changes

2021-07-05 07:57 UTC, merged

2021-07-05 10:59 UTC, Ghostkeeper commented
As discussed, it is indeed expected behaviour that Ultimaker PLA is supported in the same configurations as Generic PLA and should behave the same, so we've merged this change.