Various material profiles with all available colors added
Ultimaker/fdm_materials pull request #183
Opened 2021-09-09 17:53 UTC by x40-Community

We have a large material and print profile database from the X40 Community project that we would like to make available to everyone.

2021-09-13 07:57 UTC, nallath requested changes

2021-09-13 07:57 UTC, nallath commented on Verbatim_PETG_Black_175.xml.fdm_material
> +      <material>PET-G</material>
```suggestion
      <material>PETG</material>
```

PETG is the material type that is used everywhere else.

2021-09-13 07:57 UTC, nallath commented on Verbatim_PETG_Blue_175.xml.fdm_material
> +      <material>PET-G</material>
```suggestion
      <material>PETG</material>
```

2021-09-13 07:57 UTC, nallath commented on Verbatim_PETG_Bluetransparent_175.xml.fdm_material
> +      <material>PET-G</material>
```suggestion
      <material>PETG</material>
```

2021-09-13 07:57 UTC, nallath commented on Verbatim_PETG_Clear_175.xml.fdm_material
> +      <label>Clear PET-G</label>
```suggestion
      <label>Clear PETG</label>
```

2021-09-13 07:57 UTC, nallath commented on Verbatim_PETG_Greentransparent_175.xml.fdm_material
> +      <material>PET-G</material>
```suggestion
      <material>PETG</material>
```

2021-09-13 07:57 UTC, nallath commented on Verbatim_PETG_Red_175.xml.fdm_material
> +      <material>PET-G</material>
```suggestion
      <material>PETG</material>
```

2021-09-13 07:57 UTC, nallath commented on Verbatim_PETG_Redtransparent_175.xml.fdm_material
> +      <material>PET-G</material>
```suggestion
      <material>PETG</material>
```

2021-09-13 07:57 UTC, nallath commented on Verbatim_PETG_White_175.xml.fdm_material
> +      <label>White PET-G</label>
```suggestion
      <label>White PETG</label>
```

2021-09-16 08:49 UTC, nallath submitted a review, later dismissed

2021-11-18 15:29 UTC, Ghostkeeper commented
There is a note here about material types that may require changes to this PR: https://github.com/Ultimaker/Cura/pull/10345#issuecomment-972968258

2021-12-20 16:10 UTC, closed without merging